### ISSUE TITLE
runtime parameters like resize shape from config.pbtxt

### ISSUE THREAD

**Issue by dumbPy** [triton-inference-server/dali_backend#112]
I want to write preprocessing pipeline that I intend to reuse with multiple yolo models having different input shapes.

Some would have `512x512` input while others might have `256x256`, etc. Is there a way to keep this `resize_x` and `resize_y` parameters of `dali.fn.resize` configurable from the config.pbtxt ?

I tried digging through the examples and tried passing these to `pipeline_def` but it only expects the Pipeline initialisation kwargs. I know these kwargs can be passed from config.pbtxt.

I also saw that I can pass the `resize_x` and `resize_y` as in input and get them through `fn.external_source` but is there a way to pass these values directly in config.pbtxt instead of taking these from user input (since they are dependent on downstream model input size that the user might not have knowledge of). ?

**Comment by szalpal** [comment]
Hi @dumbPy !

Apologies for the late response.

I envision 2 scenarios you can follow:
1. You want to have a single `model.dali` (i.e. serialized DALI pipeline) model for all of your YOLO models. In this scenario, since the DALI pipeline is already serialized, your best chance would be to use `fn.external_source` and feed the model with the input. Unfortunately, Triton does not make it easy to pass constants specified in `config.pbtxt`. However, you could work this around. If you set up a Python Backend model before the DALI model, Python model might have knowledge about the shape of the YOLO model. This way, Python model can take the user input and pass it (at the minimal cost) to DALI together with the `resize` parameter.
2. The other option is to keep unserialized DALI model and then deploy it. Obviously, it's not something that can be always convenient. However, if you have a deployment step before running the server and choosing the YOLO input shape, you can parameterize DALI pipeline serialization:
```python
@pipeline_def
def pipe(rx, ry):
    inp = fn.external_source(...)
    resized = fn.resize(inp, resize_x=rx, resize_y=ry, ...)
    return resized

[...]
def serialize():
    args = args.parse_args()  # argparse in one way to pass the cmdline parameters...
    p = pipe(rx=args.rx, ry=args.ry, ...)
    p.serialize(...)
```

I hope this is going to help.

**Comment by dumbPy** [comment]
Hi @szalpal 
thank you, and sorry for my late reply :sweat_smile: 

Yes, Solution 2 is what I ended up going with since it's doesn't take much time to compile, while deploying a model.
Thanks a lot..

**Comment by chajath** [comment]
could you elaborate on option 2 please? do we serialize DALI pipeline on-the-fly in the triton container?
