### ISSUE TITLE
Using custom DALI plugins with Triton

### ISSUE THREAD

**Issue by leanrdchen00918** [triton-inference-server/dali_backend#138]
Hi! I'm trying to use custom DALI plugins with Triton and I've followed the guide in `dali_backend/docs/examples/dali_plugin/README.md`, but somehow it doesn't work. Below are the two errors encountered that really confuse me.

The first one looks like this:
![2022-07-04 10-35-14 的屏幕截图](https://user-images.githubusercontent.com/59246042/177071896-8a627665-6b7a-43f3-8af8-df1d79e9a2c6.png)
I've noticed the mismatch between the version of DALI I'm using(1.15) and the version of 'dali' TRITONBACKEND API(1.10). Is this really a problem? And if so, how can I fix it?

The second one looks like this:
![2022-07-04 10-41-21 的屏幕截图](https://user-images.githubusercontent.com/59246042/177072295-679eb324-8ec2-452c-88c7-22ed9174c83e.png)
I think it is the same problem as the one mentioned in the guide. However, I've double checked my backend configuration and I think it's fine. The plugin library locates at `/model_repo/libcustom_operation.so`, and the command I use to start the triton server is `sudo docker run 
--gpus=1 
--rm 
-p8000:8000 -p8001:8001 -p8002:8002 
-v /home/yychen/Work/triton/model_repo/:/models 
nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver 
--model-repository=/models 
--backend-config dali,plugin_libs=/models/libcustom_operation.so`

Thanks! Wish to have your help.

**Comment by leanrdchen00918** [comment]
Problem solved!
It turns out the version of libdali.so in tritonserver:22.06-py3 is 1.14. I have to switch my DALI version to 1.14(as dali_backend/DALI_VERSION points out) to serve my pipeline successfully. Is there a way to manage these versions in a more decent, like, automatic way?

**Comment by szalpal** [comment]
@leanrdchen00918 ,

Do I understand correctly, that your problem was that you were building Custom Operator with DALI 1.15 instead of 1.14?

The only convenient way of maintaining several DALI versions that comes to my mind is using `virtualenv` or conda environments.

Thank you for pointing out the potential problem with the plugin. We usually bump DALI version with every dali_backend release (every month or so), so the compatibility problem might arise. I'll try to investigate possible improvements in this field.

**Comment by leanrdchen00918** [comment]
@szalpal You are right about my mistake. Thanks a lot for your advice!
