### ISSUE TITLE
multi-ROI cropping on a single image

### ISSUE THREAD

**Issue by xiazi-yu** [triton-inference-server/dali_backend#257]
I want to use DALI to implement multi-ROI cropping on a single image, while also performing padding to maintain the aspect ratio for subsequent use with YOLOv8. How should I proceed, ensuring that the operation can be completed in one go?

**Comment by xiazi-yu** [comment]
I want to use DALI to implement multi-ROI cropping on a single image, while also performing padding to maintain the aspect ratio for subsequent use with YOLOv8. How should I proceed, ensuring that the operation can be completed in one go?

**Comment by mzient** [comment]
Hello @xiazi-yu 

The possibilities in DALI are rather limited, but some workarounds exist assuming, that you can live with:
a) crops with different position, but same size
b) crops are subsequently resized to a common size.
See [this DALI issue](https://github.com/NVIDIA/DALI/issues/1579) which explores the similar problem and possible solutions. Unfortunately, not all of them are usable in Triton.

As a side-note, I think this issue is more suited to the DALI project itself than Triton's dali_backend.

**Comment by xiazi-yu** [comment]
@mzient 
Thank you for your response. I've seen that example, but it only outputs fixed sizes, and the targets get distorted. YOLOv8's image input requires padding operations to maintain the aspect ratio. Do you have any better solutions, such as using DALI plugins or Triton's C++ backend?
