### ISSUE TITLE
 The doc seems complicated, could you give us a simple guide as how to use triton to inference the model with pre and post data processing with python code? 

### ISSUE THREAD

**Issue by Edwardmark** [triton-inference-server/dali_backend#69]
The doc seems complicated, could you give us a simple guide as how to use triton to inference the model with pre and post data processing with python code?

**Comment by szalpal** [comment]
@HoangTienDuc , if you have more questions about Python Backend, please create an issue in [python_backend repo](https://github.com/triton-inference-server/python_backend)

**Comment by szalpal** [comment]
@Edwardmark ,

as @deadeyegoodwin mentioned, good place to start would be to get accustomed to the [quickstart guide](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). If you have any specific question, don't hesitate do create an issue in dali_backend repository

**Comment by szalpal** [comment]
@chandrameenamohan ,

Unfortunately, DALI is not the best tool for raw text processing. The meat and potatos of DALI is to transfer data processing operations to the GPU. That's why we focus on image, audio and video: offloading these kinds of data bring the most benefit in terms of processing time.

I believe, that the best shot for you would be to use Python Backend for Triton. This way you still preprocess within the scope of TritonServer, while coding in python.
